services:
  editor:
    image: collab-editor:latest
    container_name: editor
    build: .
    ports:
     - "5050:5000"
    depends_on:
     - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports: 
      - "8085:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password